version: "3.8" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너들을 정의
  convenience-store-recommendation-database:
    container_name: convenience-store-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: eyxnz/convenience-store-recommendation-database
    environment:
      - MARIADB_DATABASE=convenience-store-recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
  convenience-store-recommendation-app:
    container_name: convenience-store-recommendation-app
    build: .
    depends_on:
      - convenience-store-recommendation-database
    image: eyxnz/convenience-store-recommendation-app
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
    ports:
      - "80:8080"
    restart: always