version: "3.8" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너들을 정의
  convenience-store-recommendation-redis: # 서비스명
    container_name: convenience-store-recommendation-redis # 컨테이너 명
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: eyxnz/convenience-store-recommendation-redis
    ports:
      - "6379:6379" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
  convenience-store-recommendation-database:
    container_name: convenience-store-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: eyxnz/convenience-store-recommendation-database
    environment:
      - MARIADB_DATABASE=convenience-store-recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3307:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)